baseURL = 'https://imagetoascii.github.io/'
languageCode = 'en-us'
title = 'ASCII.Art'

#ascii 
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = 'lightbi-hugo'


googleAnalytics = "G-T2KBJB0NWW"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 10

[permalinks]
  posts = '/:slug/'
  tags = 'tag/:slug/'
  
[minify]
  minifyOutput = false
  
[params]
    hometitle = 'Image to ASCII Picture Generator'
	homedescription = 'Convert cool photos into fun Text Art i.e. Notepad Art with Image to ASCII Picture Generator tool online.'
	
    tagline = 'ASCII Art'
	
    showRelatedPosts = true #for lightbi related posts
	title = 'Image to ASCII Picture Generator'
    description = "Ascii Arts"
    author = "asciiarts"
    selfHosted = true
	mainSections = ["post","posts"]
	#dateFormat = "2 January 2023"
	comments = false
	readingTime = false
	wordCount = false
	useHLJS = false
	socialShare = true
	delayDisqus = true
	summaryLength  = "9"
	gcse = false
	Lastmod = true
	rss = true 
	pagination = "10"
	hideAuthor = true
	darkMode = false

  [params.mytags] 
	go = 'Go is developed by google.'
	php = 'PHP is the most populer language for web developemnt.'



#nav main menu

[[menu.main]]
    name = "Image to ASCII"
    url = "/"
    weight = 1	



#menu for footer


	
[[menu.footer]]
    name = "Tags"
    url = "/tags/"
    weight = 10
	



