baseURL = 'https://imagetoascii.github.io/'
languageCode = 'en-us'
title = 'ASCII.Art'

#ascii 
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = 'lightbi-hugo'


googleAnalytics = "G-T2KBJB0NWW"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 10

[permalinks]
  posts = '/:slug/'
  tags = 'tag/:slug/'
  
[minify]
  minifyOutput = false
  
[params]
    hometitle = 'Image to ASCII Picture Generator'
	homedescription = 'Convert cool photos into fun Text Art i.e. Notepad Art with Image to ASCII Picture Generator tool online.'
	
    tagline = 'ASCII Art'
	
    showRelatedPosts = true #for lightbi related posts
	title = 'Image to ASCII Picture Generator'
    description = "Ascii Arts"
    author = "asciiarts"
    selfHosted = true
	mainSections = ["post","posts"]
	#dateFormat = "2 January 2023"
	comments = false
	readingTime = false
	wordCount = false
	useHLJS = false
	socialShare = true
	delayDisqus = true
	summaryLength  = "9"
	gcse = false
	Lastmod = true
	rss = true 
	pagination = "10"
	hideAuthor = true
	darkMode = false

  [params.mytags] 
	go = 'Go is developed by google.'
	php = 'PHP is the most populer language for web developemnt.'



#nav main menu

[[menu.main]]
    name = "Image to ASCII"
    url = "/"
    weight = 1	

[[menu.main]]
    name = "ASCII Art"
    url = "/ascii-art/"
    weight = 2

[[menu.main]]
    name = "ASCII Artwork"
    url = "/ascii-artwork/"
    weight = 3
	
[[menu.main]]
    name = "ASCII Drawing"
    url = "/ascii-drawing/"
    weight = 4

[[menu.main]]
    name = "ASCII picture"
    url = "/ascii-picture/"
    weight = 5



[[menu.main]]
    name = "Notepad Art"
    url = "/notepad-art/"
    weight = 6




#menu for footer

[[menu.footer]]
    name = "Tools"
    url = "/tools"
    weight = 1	

[[menu.footer]]
    name = "ASCII Banners"
    url = "/ascii-banners/"
    weight = 2

[[menu.footer]]
    name = "ASCII Graphics"
    url = "/ascii-graphics/"
    weight = 3
	
[[menu.footer]]
    name = "ASCII Image"
    url = "/ascii-image/"
    weight = 4

[[menu.footer]]
    name = "Funny TEXT Art"
    url = "/funny-text-art/"
    weight = 5



[[menu.footer]]
    name = "Middle Finger TEXT Art"
    url = "/middle-finger-text-art/"
    weight = 6
    
[[menu.footer]]
    name = "Shrek ASCII"
    url = "/shrek-ascii/"
    weight = 7
	
[[menu.footer]]
    name = "Simple ASCII Art"
    url = "/simple-ascii-art/"
    weight = 8
	
[[menu.footer]]
    name = "ASCII Art Logo"
    url = "/ascii-art-logo/"
    weight = 9
	
[[menu.footer]]
    name = "Tags"
    url = "/tags/"
    weight = 10
	



